version: '3.7'

services:

  php:
    build: ./docker/php
    volumes:
      - ./project:/project
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom-php.ini

    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: company
      MYSQL_ROOT_PASSWORD: toor
      TZ: Europe/Prague
    ports:
      - '3307:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    links:
      - db:db
    environment:
      - ADMINER_DESIGN=nette
    volumes:
      - ./config/adminer.ini:/usr/local/etc/php/conf.d/uploads.ini

  web:
    image: nginx:mainline-alpine
    restart: always
    depends_on:
      - php
    volumes:
      - ./project:/project
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '90:80'
